modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="groundbridge"
version="0.1.0-DEV"
displayName="Ground Bridge"
credits=""
authors="mistersecret312"
displayTest="MATCH_VERSION"

description='''Ground Bridge'''
[[dependencies.groundbridge]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.groundbridge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"